### ISSUE TITLE
DataSource.Error: Web.Contents with the Content option is only supported when connecting anonymously.

### ISSUE THREAD

**Issue by azeedo** [mcphee11/genesys-cloud-powerbi-direct#1]
I keep getting this error even when I have edited my data source setting to anonymous.

**Comment by mcphee11** [comment]
Have you setup the OAuth environment on the Genesys Cloud ORG as well as changed ALL the locations in the script on where the login URL is.... as im based in the ".com.au" region if you are in another region you will need to change all references to this location or you will get OAuth issues. details on the GC regions can be found here: https://developer.genesys.cloud/platform/api/

**Comment by azeedo** [comment]
Thank You for the response, I think I'm having a hard time because the query has too many moving parts, would be so kind to put a simple "get all users" query?

**Comment by mcphee11** [comment]
@azeedo here is a example of a query where you will be able to call the /api/v2/users endpoint which is a GET request to return a simple array object or "List" in PowerBi that you can then use for testing. NOTE you will need to put in your own region and clientId/Secret into the query. You will also still need to "ignore" the privacy levels. I just tested this and it worked fine if this is working please let me know so i can close the issue.



let
//Get the API Token
login_url = "https://login.mypurecloud.com.au/",
token_path = "oauth/token",
ClientID = "ENTER_YOUR_CLIENTID",
Secret = "ENTER_YOUR_SECRET",

EncodedCredentials = "Basic " & Binary.ToText(Text.ToBinary(ClientID & ":" & Secret), BinaryEncoding.Base64),

Token_Response = Json.Document(Web.Contents(login_url,
[
    RelativePath = token_path,
    Headers = [#"Content-Type"="application/x-www-form-urlencoded",#"Authorization"=EncodedCredentials],
    Content=Text.ToBinary("grant_type=client_credentials")
])),

//API query conversation details job endpoint
token = Token_Response[access_token],
api_url = "https://api.mypurecloud.com.au",
query_path = "/api/v2/users",

data= Json.Document(Web.Contents(api_url,
[
    RelativePath = query_path,
    Headers = [#"Authorization"="Bearer "&token,#"Content-Type"="applicaiton/json"]
])),

users = data[entities],
#"Converted to Table" = Table.FromList(users, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
in 

users

**Comment by azeedo** [comment]
Thank You so much for the sample, it did help me find out where the issue was.  It appears that under I had failed to assign roles to my Client Credentials.  Once I added the roles it worked like a charm.

**Comment by mcphee11** [comment]
Glad to hear it is now working I'll close this issue.
