### ISSUE TITLE
Dude 

### ISSUE THREAD

**Issue by RubenAparicioJimenez** [mcphee11/genesys-cloud-powerbi-direct#2]
Hello, 

I have a question now when you have the list of data how do you convert it into a functional table to create the reports. 

I got as far as the data extraction but I don't know how to convert it into data tables.

Thank you very much for your help.

Best regards

**Comment by mcphee11** [comment]
I dont have PowerBi installed on my laptop anymore but it you look at the second last screen shot in the readMe you will see the raw import. from this step you can use the PowerBi GUI to convert the nested JSON arrays to lists and eventually new columns through cicking on the top sections. This basiclly builds out the query code for you to then rungiving you the column names then as well you can use in building out your dashboards etc.

**Comment by Security252** [comment]
Hola, 

Muchas gracias por su ayuda , he podido expandir las columnas con los datos.

Ahora se me viene una duda porque estoy modificando la query JSON para que me traiga un cupo de datos más acotados , pero no consigo que el código acepte esa query.

Le dejo una captura a la derecha la query que quiero introducir y la izquierda el codigo en Power Query.

Muchas gracias.

Un saludo.

![Captura](https://github.com/mcphee11/genesys-cloud-powerbi-direct/assets/119040663/fa12f189-5707-40eb-97ff-6f680e007d8a)

**Comment by Security252** [comment]
Hello, 

Thank you very much for your help, I have been able to expand the columns with the data.

Now I have a doubt because I am modifying the JSON query to bring me a more limited amount of data, but I can't get the code to accept that query.

I leave a screenshot on the right the query that I want to enter and the left the code in Power Query.

Thank you very much.


![Captura](https://github.com/mcphee11/genesys-cloud-powerbi-direct/assets/119040663/5d50c50a-3be0-4da2-949e-58deca80184c)

**Comment by mcphee11** [comment]
interesting... that should work. You are missing the "startOfDayIntervalMatching" boolean but thats not a required field. Have you tried to use this in the "API Explorer" https://developer.genesys.cloud/devapps/api-explorer-standalone as the only thing I can think of is that your divisionId is wrong etc specifc to your ORG.

I assume when you put it into the query you add the required extra " around the keys and values? as i have in my example.

If none of this works please provide the error you get back.
